ERRORS_DICT = (
    # RMON-MIB
    {'name': 'CRC Error',
     'OID': 'etherStatsCRCAlignErrors',
     'MIB': 'RMON-MIB'},
    {'name': 'Undersize',
     'OID': 'etherStatsUndersizePkts',
     'MIB': 'RMON-MIB'},
    {'name': 'Oversize',
     'OID': 'etherStatsOversizePkts',
     'MIB': 'RMON-MIB'},
    {'name': 'Fragments',
     'OID': 'etherStatsFragments',
     'MIB': 'RMON-MIB'},
    {'name': 'Jabbers',
     'OID': 'etherStatsJabbers',
     'MIB': 'RMON-MIB'},
    {'name': 'Drop Events',
     'OID': 'etherStatsDropEvents',
     'MIB': 'RMON-MIB'},

    # EtherLike-MIB
    {'name': 'Single Collision',
     'OID': 'dot3StatsSingleCollisionFrames',
     'MIB': 'EtherLike-MIB'},
    {'name': 'Excessive Deferral',
     'OID': 'dot3StatsDeferredTransmissions',
     'MIB': 'EtherLike-MIB'},
    {'name': 'Late Collision',
     'OID': 'dot3StatsLateCollisions',
     'MIB': 'EtherLike-MIB'},
    {'name': 'Excessive Collision',
     'OID': 'dot3StatsExcessiveCollisions',
     'MIB': 'EtherLike-MIB'},
    {'name': 'Symbol Error',
     'OID': 'dot3StatsSymbolErrors',
     'MIB': 'EtherLike-MIB'},
)
